# Homework 1 - Numpy

For all the questions, print the results with a variable of your choice (e.g., Z)

#### 1. Import the numpy package under the name `np` 

In [86]:
import numpy as np

#### 2. Create a vector with values ranging from 10 to 49 

In [87]:
a_vector=np.array(np.arange(10,50))
print(a_vector)
type(a_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


numpy.ndarray

#### 3. Reverse a vector (first element becomes last) 

In [88]:
# solution2 - without using loop, but simply using slicing (much more efficient)
print(a_vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 4. Create a 3x3 matrix with values ranging from 0 to 8 

In [89]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 5. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [90]:
q5=np.array([1,2,0,0,4,0])

non_zero_elements = np.nonzero(q5)
print('Found non-zero elements. The indices are ','q5',[*non_zero_elements[0]])

Found non-zero elements. The indices are  q5 [0, 1, 4]


#### 6. Create a 3x3 identity matrix 

In [91]:
iden33=np.eye(3,3)

print(iden33)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 7. Create a 3x3x3 array with random values 

In [92]:
q7 = np.random.random((3, 3, 3))
print(q7)

[[[0.27588427 0.30751188 0.34178869]
  [0.60408011 0.52509682 0.18595629]
  [0.06980329 0.4745483  0.06818107]]

 [[0.05078067 0.58595206 0.43464629]
  [0.25060128 0.60552496 0.50602549]
  [0.02685317 0.16319469 0.84095201]]

 [[0.06850464 0.66840776 0.74645432]
  [0.41674068 0.02000948 0.65414624]
  [0.9736612  0.74189354 0.37319191]]]


#### 8. Create a 10x10 array with random values and find the minimum and maximum values 

In [93]:
q8 = np.random.random((10,10))
print('the minimum value is {}, and the maximum is {}'.format(q8.min(), q8.max()))

the minimum value is 0.027042280652201378, and the maximum is 0.9958869843958635


#### 9. Create a checkerboard 8x8 matrix using np.array([0,1],[1,0]) and the tile function  

In [94]:
q9=np.array([[0,1],[1,0]])
np.tile(q9,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [95]:
q10= np.dot(np.random.random((5,3)), np.random.random((3,2)))
print(q10)

[[0.28828211 1.13327815]
 [0.12139967 0.45526759]
 [0.10757691 0.52918242]
 [0.0550395  0.30474362]
 [0.1878802  0.71201906]]


#### 11. Create a 5x5 matrix with row values ranging from 0 to 4 using tile function as follows:


In [96]:
q11=np.arange(5)

print(np.tile(q11,(5,1)))

#or

print(np.tile(q11,5).reshape(5,5))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 12. Create a 5x5 matrix with row values ranging from 0 to 4 using broadcasting


In [97]:
q12=np.arange(5)
zero_matrix=np.zeros((5,5))

broad_matrix = zero_matrix+q12
print(broad_matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 13. Create a random vector of size 10 and sort it 

In [98]:
q13=np.random.random(10)
sorted(q13)

[0.0032538987577808154,
 0.006827623003335281,
 0.07179759627295079,
 0.07852703280158058,
 0.12603533794053567,
 0.16727792351043036,
 0.4424815269127158,
 0.5413151736627555,
 0.641725958226309,
 0.859615359271129]

#### 14. Subtract the mean of each row

X = np.random.rand(5,10)

In [99]:
X=np.random.rand(5,10)
subtracted_matrix=(X.T-np.mean(X, axis=1)).T

print(subtracted_matrix)

[[-0.50313375  0.11450965 -0.11485114  0.0747761   0.2493353   0.26102913
  -0.04092149  0.11046307 -0.19012874  0.03892186]
 [ 0.26001294 -0.11234043  0.31118824 -0.51065753 -0.41636854  0.02611472
   0.14125976  0.35872387 -0.14587687  0.08794384]
 [-0.20626826  0.43874213 -0.30783278  0.03289921 -0.24864019 -0.16705876
  -0.28947008  0.33796997  0.57134767 -0.16168891]
 [ 0.39115133  0.21457637  0.13713627  0.16475772 -0.29458863 -0.55500178
   0.26817312 -0.35386816 -0.04439043  0.07205419]
 [ 0.22590441  0.08002157  0.45252341 -0.43575988  0.30267629 -0.42656893
   0.2027624   0.28114524 -0.42391461 -0.2587899 ]]


#### 15. Create, 10 by 10 multiplication table from 1 to 10

In [100]:
np.arange(1,11)*(np.arange(1,11).reshape(10,1))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [101]:
#another solution using 'newaxis' method
a = np.arange(1,11)
b = a[:, np.newaxis]
print(a*b)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


#### 16. How to get the diagonal of a dot product? 

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [102]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.32862874, 0.57580171, 1.46594751, 1.858579  , 1.00289937])

#### 17. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [103]:
q17 = np.array([1, 2, 3, 4, 5])

#create a vector made out of zeros, which length is 3 consecutive zeros interleaved between each value of q17 + q17
zeros_vector=np.zeros(3*(len(q17)-1)+len(q17))

#replacing zeros with q17
zeros_vector[::4] = q17

print(zeros_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 18. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

In [104]:
#A = np.random.randint(0,5,(8,3))
#B = np.random.randint(0,5,(2,2))
# skipped the question

#### 19. How to swap two rows of an array? Generate an array from 0 to 24, and reshape it 5 by 5 and swap first two rows of the array

In [105]:
q19 = np.arange(25).reshape(5,5)
print('original array:\n',q19)

q19[[0,1]] = q19[[1,0]]
print('changed array:\n',q19)

original array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
changed array:
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 20. How to find the most frequent value in an array? 

Z = np.random.randint(0,10,50). hint: np.bincount, np.argmax

In [106]:
Z = np.random.randint(0,10,50)
print(Z)

print('The most frequent value in this array is {}'.format(np.bincount(Z).argmax()))

[5 0 1 7 1 0 5 6 8 1 6 3 1 5 7 9 4 1 2 4 7 8 0 8 5 1 9 5 7 2 5 3 5 9 8 6 6
 8 0 8 9 0 0 0 0 2 5 7 9 0]
The most frequent value in this array is 0


#### 21. How to get the n largest values of an array?

start with 
Z = np.arange(10000);
np.random.shuffle(Z)
, Hint: np.argsort

In [107]:
n=3 #n is an arbitrary number;

Z = np.arange(10000)
np.random.shuffle(Z)
print(Z)

indices_from_the_smallest = np.argsort(Z)
print('the {} largest values of array Z are {}'.format(n,Z[indices_from_the_smallest[-n:]]))

[2595 9229 2333 ... 7826 5776 7911]
the 3 largest values of array Z are [9997 9998 9999]


#### 22. Given a two dimensional array, how to extract unique rows? 

Hint: np.unique

In [108]:
q22= np.random.randint(3, 6,(1000,2))
np.unique(q22, axis = 0)

array([[3, 3],
       [3, 4],
       [3, 5],
       [4, 3],
       [4, 4],
       [4, 5],
       [5, 3],
       [5, 4],
       [5, 5]])

#### 23. How to compute averages using a sliding window over an array? 

make a function with two arguments, arry and size of the sliding window, def moving_avg(arr, n)


In [109]:
def moving_avg(arr,n):
    windows=[]
    averages=[]
    for i in range(len(arr)-(n-1)):
        windows.append(arr[i:i+n])
        averages.append(windows[i].mean())
    return averages



one_to_ten=np.arange(1,11)
print(one_to_ten)

moving_avg(one_to_ten,n=3)

[ 1  2  3  4  5  6  7  8  9 10]


[2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

#### 24. Find the indices of elements from 4 by 4 random matrix (0-1) which are larger than 0.5

Print a list of tuples indicating the index for row and column


In [110]:
q24=np.random.random((4,4))
print(q24)

larger_than=(q24>0.5)
print(larger_than.nonzero())

print([*zip(larger_than.nonzero()[0],larger_than.nonzero()[1])])

[[0.11795557 0.68279698 0.21381364 0.11476022]
 [0.78342981 0.52189386 0.87348794 0.39251956]
 [0.90942362 0.55271971 0.42960154 0.43347179]
 [0.33787366 0.94468349 0.80952829 0.60712477]]
(array([0, 1, 1, 1, 2, 2, 3, 3, 3], dtype=int64), array([1, 0, 1, 2, 0, 1, 1, 2, 3], dtype=int64))
[(0, 1), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (3, 1), (3, 2), (3, 3)]


#### 25. Write a function returning distance between two points

In [111]:
def distance(point1, point2):
    return (np.sqrt(np.sum((p1-p2)**2)))

#p1 and p2 are array which are consist of x and y coordinates respectively.(x,y are arbitrary integers between -100 and 100)
p1 = np.random.randint(-100,100,(2,1))
p2 = np.random.randint(-100,100,(2,1))

print(p1)
print(p2)


print(distance(p1, p2))

[[ 98]
 [-11]]
[[-98]
 [-17]]
196.09181522949905
